[package]
name = "zigzag-score"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
async-graphql = "7.0"
linera-sdk = "0.15.0"         # <--- This is the one you were missing
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"